---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    ansible.builtin.yum:
      update_cache: yes

  - name: install vim package
    ansible.builtin.yum:
      name: vim
      state: latest

  - name: install nano package
    ansible.builtin.yum:
      name: nano
      state: latest

  - name: install chrony package
    ansible.builtin.yum:
      name: chrony
      state: latest
      update_cache: yes

  - name: deploy chrony.conf template
    template:
      src: /root/ansible/chrony.conf
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: retart chrony service
    service:
      name: chronyd
      state: restarted
