---

- hosts: all
  become: true
  tasks:

  - name: Install updates
    tags: always
    package:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install Chrony
    package:
     name: 
        - "{{ chrony_package }}"
      state: latest

  - name: install vim and nano packages
    package:
      name: 
        - "{{ vim_package }}" 
        - "{{ nano_package }}"
      state: latest

  - name: deploy chrony.conf template
    ansible.builtin.copy:
      src: /root/ansible/chrony.conf
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: chrony

  - name: start the chrony service
    service:
      name: chronyd
      state: started
      enabled: yes
    when: chrony.changed

- hosts: Cent7-02
  become: true
  tasks:

  - name: Install httpd service
    tags: apache,apache2,httpd
    package:
      name: httpd
      state: latest

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
