- name: Install httpd
  tags: apache,apache2,httpd
  package: 
    name: "{{ httpd_package_name }}"
    state: latest

- name: copy default file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/http/index.html
    owner: root
    group: root
    mode: 0644 
