- name: Install Chrony 
  ansible.builtin.package: 
    name: chrony
    state: latest

- name: Deploy the chrony conf file
  ansible.builtin.copy:
    src: files/chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  register: chrony

- name: Start the chrony service
  ansible.builtin.service:
    name: chronyd 
    state: started
    enabled: yes
