---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Chrony
    ansible.builtin.package:
      name: 
        - "{{ chrony_package }}"
      state: latest
      update_cache: true

  - name: Create user simone
    ansible.builtin.user:
      name: simone
      groups: root

- hosts: Cent7-01
  tags: centos,vim,nano
  become: true

  tasks:
  - name: install vim and nano packages
    ansible.builtin.package:
      name: 
        - "{{ vim_package }}" 
        - "{{ nano_package }}"
      state: latest

- hosts: Cent7-02
  tags: httpd
  become: true
  tasks:

  - name: Install httpd service
    tags: apache,apache2,httpd
    ansible.builtin.package:
      name:
       - "{{ httpd_package }}"
      state: latest

- hosts: web_servers
  tags: httpd
  become: true
  tasks:

  - name: Update httpd
    ansible.builtin.package:
      name: httpd
      state: latest

 
